### ISSUE TITLE
Please invite me to the GitHub Organization

### ISSUE THREAD

**Issue by 3mmarYasser** [elevanceit/.github#2]
### Name

Ammar Yasser

### Email

ammar.yasseer.mohamed@gmail.com

### Phone (if applicable)

+201012941239

### Additional Context

I met Elevance Innovation Technology through Dmitry Selikhov on LinkedIn, who mentioned that you are hiring and developing an outstaff platform.

**Comment by idimetrix** [comment]
Invited @3mmarYasser
